#!/usr/bin/env python3
# Generates src/data.h: embeds AXV.FON (256x19 glyphs), KU.INC's ku_tab
# (128 bytes, KU 80h-FFh -> TIS-620), and HELP_LINUX.TXT (TIS-620 +
# WordStar style bytes -- HELP.TXT adapted for this Linux/X11 port, see
# build_help_linux.py) as C arrays. Font/ku_tab/status strings are the
# exact same assets as the Windows port; only the help text differs
# between ports. Run once; re-run if the source assets change.
#
# Paths are relative to this script's own location, so it works no matter
# where the repo is cloned to.
import os, re

HERE = os.path.dirname(os.path.abspath(__file__))
DOS = os.path.join(HERE, '..', 'dos')
OUT = os.path.join(HERE, 'src', 'data.h')

def carray(name, data, ctype='unsigned char'):
    lines = [f'static const {ctype} {name}[{len(data)}] = {{']
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        lines.append('    ' + ','.join(str(b) for b in chunk) + ',')
    lines.append('};')
    return '\n'.join(lines)

# 1) font
with open(os.path.join(DOS, 'AXV.FON'), 'rb') as f:
    font = f.read()
assert len(font) == 256*19, len(font)

# 2) ku_tab -- parse "db a,b,c" lines from KU.INC
with open(os.path.join(DOS, 'KU.INC')) as f:
    ku_src = f.read()
ku_bytes = []
for m in re.finditer(r'db\s+([0-9,\s]+)', ku_src):
    ku_bytes += [int(x) for x in m.group(1).replace('\n',' ').split(',') if x.strip()]
assert len(ku_bytes) == 128, len(ku_bytes)

# 3) help text -- raw bytes, truncated at first 1Ah (^Z) if present (00h is
#    NOT a terminator). HELP_LINUX.TXT (this directory) is HELP.TXT
#    adapted for this Linux/X11 port, see build_help_linux.py.
with open(os.path.join(HERE, 'HELP_LINUX.TXT'), 'rb') as f:
    help_raw = f.read()
if 0x1A in help_raw:
    help_raw = help_raw[:help_raw.index(0x1A)]

# 4) status-bar right-hint string (stl_right, TIS-620 + 02h bold-toggle
#    markers) and the KU/TIS mode-label strings, from STATUS.INC
with open(os.path.join(DOS, 'STATUS.INC')) as f:
    status_src = f.read()

def parse_block(src, label):
    m = re.search(label + r':\s*\n((?:\s*db\s+[0-9A-Fa-fh,\s]+\n)+)', src)
    assert m, label
    vals = []
    for line in m.group(1).splitlines():
        line = line.strip()
        if not line.startswith('db'):
            continue
        for tok in line[2:].split(','):
            tok = tok.strip()
            if not tok:
                continue
            vals.append(int(tok[:-1], 16) if tok.lower().endswith('h') else int(tok))
    return bytes(vals)

stl_right = parse_block(status_src, 'stl_right')
sw_ku = parse_block(status_src, 'sw_ku')
sw_tis = parse_block(status_src, 'sw_tis')

with open(OUT, 'w') as f:
    f.write('/* Auto-generated by gen_data.py -- do not edit by hand. */\n')
    f.write('#pragma once\n\n')
    f.write(carray('g_font', font))
    f.write('\n\n')
    f.write(carray('g_ku_tab', bytes(ku_bytes)))
    f.write('\n\n')
    f.write(f'#define HELP_LEN {len(help_raw)}\n')
    f.write(carray('g_help_data', help_raw))
    f.write('\n\n')
    f.write(f'#define STL_RIGHT_LEN {len(stl_right)}\n')
    f.write(carray('g_stl_right', stl_right))
    f.write('\n\n')
    f.write(f'#define SW_KU_LEN {len(sw_ku)}\n')
    f.write(carray('g_sw_ku', sw_ku))
    f.write('\n\n')
    f.write(f'#define SW_TIS_LEN {len(sw_tis)}\n')
    f.write(carray('g_sw_tis', sw_tis))
    f.write('\n')

print('wrote', OUT, 'font', len(font), 'ku_tab', len(ku_bytes), 'help', len(help_raw),
      'stl_right', len(stl_right), 'sw_ku', len(sw_ku), 'sw_tis', len(sw_tis))
